server:
  port: 8080  #????????
spring:
  datasource: #???
    druid:
      url: jdbc:mysql://localhost:3306/vue_video?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  mail:  #??????
    host: smtp.qq.com   #?????SMTP???
    username: 2601449063@qq.com  #???????
    password: biqlfbqkkybaecfb    #???????
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: localhost #redis?????
    password: root #redis???????
    port: 6379 #redis??????
  servlet:
    multipart:
      enabled: true
      #?????????
      max-file-size: 200MB
      #??????????
      max-request-size: 500MB
mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.vue_video.pojo
  configuration:
    #??????
    map-underscore-to-camel-case: true
